### ISSUE TITLE
Add Transitions with Material Motion

### ISSUE THREAD

**Issue by ELTEGANI** [OMIsie11/SpaceXFollower#5]
I have a PR suggestion to add [Beautiful Transitions with Material Motion](https://medium.com/androiddevelopers/material-motion-with-mdc-c1f09bb90bf9) in Actual stats labels(capsules, Launches, and Cores). If it's okay assign me to this issue. 
@OMIsie11

**Comment by OMIsie11** [comment]
As far as I remember correctly, those transitions should be already added when navigating to details of particular Launch/Core/Capsule, but correct me if I am wrong.
So, do You want to add it on when navigating from Dashboard to Launches/Capsules/Cores screens?
Seems like a good idea 😄

**Comment by ELTEGANI** [comment]
> As far as I remember correctly, those transitions should be already added when navigating to details of particular Launch/Core/Capsule, but correct me if I am wrong.
> So, do You want to add it on when navigating from Dashboard to Launches/Capsules/Cores screens?
> Seems like a good idea

Yes, You are right those transitions are used when one thing turns into another thing. Yes, it seems a good idea I want to add them when navigation from actual stats labels in the dashboard into their screens.
Thanks :+1:

**Comment by OMIsie11** [comment]
Okay, so open a Pull Request when You are done, thanks 😃

**Comment by OMIsie11** [comment]
Added by @ELTEGANI in 0e9fca4
